name: ifs-amortized
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pytorch=2.3
  - torchvision=0.18
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - matplotlib
  - pyyaml
